/**
 * Generate typed API client with React hooks from OpenAPI spec.
 *
 * Usage: pnpm api:generate
 *
 * Reads openapi.json and outputs src/generated/api-client.ts with:
 *  - TypeScript interfaces for every schema
 *  - A typed fetch wrapper (apiClient)
 *  - React hooks for each endpoint (useQuery-style for GET, useMutation-style for POST/PATCH/DELETE)
 */
import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const specPath = resolve(__dirname, "../openapi.json");
const outPath = resolve(__dirname, "../src/generated/api-client.ts");

type OpenAPIDoc = {
  paths: Record<string, Record<string, PathItem>>;
  components?: { schemas?: Record<string, SchemaObj> };
};

type PathItem = {
  summary?: string;
  tags?: string[];
  parameters?: Array<{
    name: string;
    in: string;
    required?: boolean;
    schema?: SchemaObj;
  }>;
  requestBody?: {
    content?: { "application/json"?: { schema?: SchemaObj } };
  };
  responses?: Record<
    string,
    { content?: { "application/json"?: { schema?: SchemaObj } } }
  >;
};

type SchemaObj = {
  type?: string;
  $ref?: string;
  properties?: Record<string, SchemaObj>;
  items?: SchemaObj;
  required?: string[];
  nullable?: boolean;
  allOf?: SchemaObj[];
  oneOf?: SchemaObj[];
  anyOf?: SchemaObj[];
  enum?: string[];
  additionalProperties?: boolean | SchemaObj;
};

// ─── Read spec ───────────────────────────────────────────────────

let spec: OpenAPIDoc;
try {
  spec = JSON.parse(readFileSync(specPath, "utf-8"));
} catch {
  console.error(
    "Could not read openapi.json. Run `pnpm openapi:generate` first."
  );
  process.exit(1);
}

const schemas = spec.components?.schemas ?? {};

// ─── Schema → TypeScript ─────────────────────────────────────────

function refToName(ref: string): string {
  return ref.replace("#/components/schemas/", "");
}

function schemaToTs(s: SchemaObj, indent = 0): string {
  if (!s) return "unknown";

  if (s.$ref) return refToName(s.$ref);

  if (s.allOf) {
    return s.allOf.map((sub) => schemaToTs(sub, indent)).join(" & ");
  }

  if (s.oneOf || s.anyOf) {
    const variants = s.oneOf || s.anyOf || [];
    return variants.map((sub) => schemaToTs(sub, indent)).join(" | ");
  }

  if (s.enum) {
    return s.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  if (s.type === "array") {
    const itemType = s.items ? schemaToTs(s.items, indent) : "unknown";
    return `${itemType}[]`;
  }

  if (s.type === "object" || s.properties) {
    const props = s.properties ?? {};
    const required = new Set(s.required ?? []);
    const pad = "  ".repeat(indent + 1);
    const closePad = "  ".repeat(indent);

    if (Object.keys(props).length === 0) {
      if (s.additionalProperties) {
        const valType =
          typeof s.additionalProperties === "object"
            ? schemaToTs(s.additionalProperties, indent)
            : "unknown";
        return `Record<string, ${valType}>`;
      }
      return "Record<string, unknown>";
    }

    const lines = Object.entries(props).map(([key, val]) => {
      const opt = required.has(key) ? "" : "?";
      const nullable = val.nullable ? " | null" : "";
      return `${pad}${key}${opt}: ${schemaToTs(val, indent + 1)}${nullable};`;
    });

    return `{\n${lines.join("\n")}\n${closePad}}`;
  }

  if (s.type === "string") return "string";
  if (s.type === "number" || s.type === "integer") return "number";
  if (s.type === "boolean") return "boolean";
  if (s.type === "null") return "null";

  // Nullable wrapper
  if (s.nullable) {
    const base = { ...s, nullable: undefined };
    return `${schemaToTs(base, indent)} | null`;
  }

  return "unknown";
}

// ─── Generate interfaces ─────────────────────────────────────────

const lines: string[] = [
  "// ──────────────────────────────────────────────────────────────────",
  "// AUTO-GENERATED by scripts/generate-api-client.ts",
  "// Do not edit manually. Re-run: pnpm api:generate",
  "// ──────────────────────────────────────────────────────────────────",
  "",
  'import { useState, useEffect, useCallback, useRef } from "react";',
  "",
  "// ─── API Types ──────────────────────────────────────────────────",
  "",
];

for (const [name, schema] of Object.entries(schemas)) {
  lines.push(`export type ${name} = ${schemaToTs(schema)};`);
  lines.push("");
}

// ApiResponse wrapper type
lines.push(
  "export type ApiResponse<T> = {",
  "  data: T | null;",
  "  error: string | null;",
  "  meta?: { total?: number; page?: number; limit?: number };",
  "};",
  ""
);

// ─── Fetch wrapper ───────────────────────────────────────────────

lines.push(
  "// ─── Fetch Client ────────────────────────────────────────────────",
  "",
  "type FetchOptions = {",
  "  method?: string;",
  "  body?: unknown;",
  "  params?: Record<string, string | number | undefined>;",
  "};",
  "",
  "async function apiClient<T>(path: string, opts: FetchOptions = {}): Promise<ApiResponse<T>> {",
  "  const { method = 'GET', body, params } = opts;",
  "",
  "  let url = path;",
  "  if (params) {",
  "    const sp = new URLSearchParams();",
  "    for (const [k, v] of Object.entries(params)) {",
  "      if (v !== undefined) sp.set(k, String(v));",
  "    }",
  "    const qs = sp.toString();",
  "    if (qs) url += '?' + qs;",
  "  }",
  "",
  "  const res = await fetch(url, {",
  "    method,",
  "    headers: body ? { 'Content-Type': 'application/json' } : undefined,",
  "    body: body ? JSON.stringify(body) : undefined,",
  "  });",
  "",
  "  return res.json();",
  "}",
  ""
);

// ─── Query hook ──────────────────────────────────────────────────

lines.push(
  "// ─── Hooks ─────────────────────────────────────────────────────",
  "",
  "type UseQueryResult<T> = {",
  "  data: T | null;",
  "  error: string | null;",
  "  loading: boolean;",
  "  refetch: () => void;",
  "};",
  "",
  "type UseMutationResult<TData, TInput> = {",
  "  mutate: (input: TInput) => Promise<ApiResponse<TData>>;",
  "  data: TData | null;",
  "  error: string | null;",
  "  loading: boolean;",
  "};",
  ""
);

// ─── Generate hooks for each path ────────────────────────────────

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
}

function hookName(method: string, path: string): string {
  const segments = path
    .replace(/^\/api\//, "")
    .replace(/\{(\w+)\}/g, "By$1")
    .split("/");
  const name = toPascalCase(segments.join("-"));

  if (method === "get") return `use${name}`;
  if (method === "post") return `use${name}Mutation`;
  if (method === "patch") return `useUpdate${name}`;
  if (method === "delete") return `useDelete${name}`;
  return `use${toPascalCase(method)}${name}`;
}

function extractResponseType(item: PathItem): string {
  const resp = item.responses?.["200"];
  const schema = resp?.content?.["application/json"]?.schema;
  if (!schema) return "unknown";

  // It's wrapped in ApiResponse: { data, error, meta }
  // Extract the data field type
  const dataSchema = schema.properties?.data;
  if (dataSchema) return schemaToTs(dataSchema);

  return schemaToTs(schema);
}

function extractRequestType(item: PathItem): string | null {
  const schema =
    item.requestBody?.content?.["application/json"]?.schema;
  if (!schema) return null;
  return schemaToTs(schema);
}

function hasPathParams(path: string): string[] {
  const matches = path.match(/\{(\w+)\}/g) || [];
  return matches.map((m) => m.replace(/[{}]/g, ""));
}

function hasQueryParams(item: PathItem): Array<{ name: string; required: boolean }> {
  return (item.parameters ?? [])
    .filter((p) => p.in === "query")
    .map((p) => ({ name: p.name, required: p.required ?? false }));
}

for (const [path, methods] of Object.entries(spec.paths)) {
  for (const [method, item] of Object.entries(methods)) {
    const name = hookName(method, path);
    const responseType = extractResponseType(item);
    const pathParams = hasPathParams(path);
    const queryParams = hasQueryParams(item);
    const summary = item.summary ? ` ${item.summary}` : "";

    if (method === "get") {
      // Build function signature params
      const fnParams: string[] = [];
      if (pathParams.length) {
        fnParams.push(...pathParams.map((p) => `${p}: string`));
      }
      if (queryParams.length) {
        const qProps = queryParams
          .map((q) => `${q.name}${q.required ? "" : "?"}: string`)
          .join("; ");
        fnParams.push(`params?: { ${qProps} }`);
      }

      const paramsArg = fnParams.join(", ");

      // Build the URL
      let urlExpr = `"${path}"`;
      for (const p of pathParams) {
        urlExpr = urlExpr.replace(`{${p}}`, `\${${p}}`);
        urlExpr = "`" + urlExpr.slice(1, -1) + "`";
      }

      lines.push(`/**${summary} */`);
      lines.push(
        `export function ${name}(${paramsArg}): UseQueryResult<${responseType}> {`
      );
      lines.push("  const [data, setData] = useState<" + responseType + " | null>(null);");
      lines.push("  const [error, setError] = useState<string | null>(null);");
      lines.push("  const [loading, setLoading] = useState(true);");
      lines.push("  const mountedRef = useRef(true);");
      lines.push("");
      lines.push("  const refetch = useCallback(() => {");
      lines.push("    setLoading(true);");

      if (queryParams.length) {
        lines.push(
          `    apiClient<${responseType}>(${urlExpr}, { params: params as Record<string, string | number | undefined> })`
        );
      } else {
        lines.push(`    apiClient<${responseType}>(${urlExpr})`);
      }

      lines.push("      .then((res) => {");
      lines.push("        if (!mountedRef.current) return;");
      lines.push("        setData(res.data);");
      lines.push("        setError(res.error);");
      lines.push("      })");
      lines.push("      .catch((e) => {");
      lines.push("        if (!mountedRef.current) return;");
      lines.push("        setError(e.message);");
      lines.push("      })");
      lines.push("      .finally(() => {");
      lines.push("        if (mountedRef.current) setLoading(false);");
      lines.push("      });");

      // Dep array
      const deps = [...pathParams];
      if (queryParams.length) deps.push("params");
      lines.push(`  }, [${deps.join(", ")}]);`);
      lines.push("");
      lines.push("  useEffect(() => {");
      lines.push("    mountedRef.current = true;");
      lines.push("    refetch();");
      lines.push("    return () => { mountedRef.current = false; };");
      lines.push("  }, [refetch]);");
      lines.push("");
      lines.push("  return { data, error, loading, refetch };");
      lines.push("}");
      lines.push("");
    } else {
      // Mutation hooks (POST, PATCH, DELETE)
      const requestType = extractRequestType(item);
      const inputType = requestType || "void";
      const pathParamStr = pathParams.length
        ? pathParams.map((p) => `${p}: string`).join(", ") + ", "
        : "";

      let urlExpr = `"${path}"`;
      for (const p of pathParams) {
        urlExpr = urlExpr.replace(`{${p}}`, `\${${p}}`);
        urlExpr = "`" + urlExpr.slice(1, -1) + "`";
      }

      lines.push(`/**${summary} */`);
      lines.push(
        `export function ${name}(${pathParamStr}): UseMutationResult<${responseType}, ${inputType}> {`
      );
      lines.push(
        "  const [data, setData] = useState<" + responseType + " | null>(null);"
      );
      lines.push("  const [error, setError] = useState<string | null>(null);");
      lines.push("  const [loading, setLoading] = useState(false);");
      lines.push("");
      lines.push(
        `  const mutate = useCallback(async (input: ${inputType}): Promise<ApiResponse<${responseType}>> => {`
      );
      lines.push("    setLoading(true);");
      lines.push("    setError(null);");
      lines.push("    try {");
      lines.push(
        `      const res = await apiClient<${responseType}>(${urlExpr}, {`
      );
      lines.push(`        method: "${method.toUpperCase()}",`);
      if (inputType !== "void") {
        lines.push("        body: input,");
      }
      lines.push("      });");
      lines.push("      setData(res.data);");
      lines.push("      setError(res.error);");
      lines.push("      return res;");
      lines.push("    } catch (e: any) {");
      lines.push("      setError(e.message);");
      lines.push(
        "      return { data: null, error: e.message, meta: undefined };"
      );
      lines.push("    } finally {");
      lines.push("      setLoading(false);");
      lines.push("    }");
      lines.push("  }, []);");
      lines.push("");
      lines.push("  return { mutate, data, error, loading };");
      lines.push("}");
      lines.push("");
    }
  }
}

// ─── Write output ────────────────────────────────────────────────

writeFileSync(outPath, lines.join("\n") + "\n");
console.log(`API client generated at ${outPath}`);
console.log(`  - ${Object.keys(schemas).length} types`);
console.log(
  `  - ${Object.values(spec.paths).reduce((n, m) => n + Object.keys(m).length, 0)} hooks`
);
